[package]
name = "unob-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Iamanro <https://iamanro.dev>"]
license = "AGPL-3.0-or-later AND MIT-0"
description = "Závěrečné práce na Univerzitě obrany"
categories = ["thesis"]
compiler = "0.15.1"
repository = "https://github.com/iamanro/uo-thesis"
disciplines = ["computer-science"]
keywords = ["thesis", "czech", "university of defence", "unob", "bachelor", "master", "dissertation"]
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

[tool.unob-thesis]
languages = ["cs", "en"]